version: 2

env:
  - GO_VERSION=1.25.5
  - TOOLCHAINS_VERSION=v0.2.0
  - GORELEASER_VERSION=2.13.2
  - TINI_VERSION=v0.19.0
  - COSIGN_VERSION=2.5.3

builds:
  - skip: true

# NOTE: needs to be run with `--parallelism=1`, as goreleaser and
# goreleaser-pro depends on base.
dockers_v2:
  - id: base
    images:
      - "goreleaser/goreleaser-cross-base"
      - "ghcr.io/goreleaser/goreleaser-cross-base"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile.base
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - docker.sources
      - entrypoint.sh
    build_args:
      GO_VERSION: "{{ .Env.GO_VERSION }}"
      TINI_VERSION: "{{ .Env.TINI_VERSION }}"
      COSIGN_VERSION: "{{ .Env.COSIGN_VERSION }}"
      TOOLCHAINS_TAG: "{{ .Env.TOOLCHAINS_VERSION }}"

  - id: goreleaser
    images:
      - "goreleaser/goreleaser-cross"
      - "ghcr.io/goreleaser/goreleaser-cross"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      BASE_VERSION: "{{ .Tag }}"
      GORELEASER_VERSION: "{{ .Env.GORELEASER_VERSION }}"

  - id: goreleaser-pro
    images:
      - "goreleaser/goreleaser-cross-pro"
      - "ghcr.io/goreleaser/goreleaser-cross-pro"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      BASE_VERSION: "{{ .Tag }}"
      GORELEASER_VERSION: "{{ .Env.GORELEASER_VERSION }}"
      GORELEASER_DISTRIBUTION: "-pro"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
