---
name: goreleaser-bump

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "GoReleaser version tag (e.g., v2.13.2)"
        required: true

jobs:
  goreleaser-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in .goreleaser.yaml
        run: |
          sed -i -e "s/GORELEASER_VERSION=.*/GORELEASER_VERSION=${{ github.event.inputs.tag }}/g" .env

      - name: Commit new version
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "feat: bump goreleaser to ${{ github.event.inputs.tag }}"
          branch: master
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: actions-user <actions@github.com>
